name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.8, 3.7]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python ${{ matrix.python-version }}'
      uses: actions/setup-python@v2
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Install chromedriver and geckodriver (Firefox Webdriver) via seleniumbase
      run: |
        sudo apt install google-chrome-stable firefox
        pip3 install seleniumbase
        seleniumbase install chromedriver
        seleniumbase install geckodriver

    - name: 'Install package'
      run: |
        pip3 install poetry tox-gh-actions
        make install

    - name: 'List installed packages'
      run: |
        poetry run pip freeze

    - name: 'List all tox test environments'
      run: |
        make tox-listenvs

    - name: 'Run tests with Python v${{ matrix.python-version }}'
      run: |
        poetry run tox

    - name: 'Upload coverage report'
      run: bash <(curl -s https://codecov.io/bash)

    - name: 'Run linters'
      if: matrix.python-version == '3.8'
      run: |
        make lint
